# Generated by Django 2.0.7 on 2018-08-15 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='exam_image')),
                ('description', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('timer', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Free_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Multi_choice_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multi_variant', models.CharField(max_length=50)),
                ('multi_description', models.CharField(max_length=1000)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='one_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_variant', models.CharField(max_length=50)),
                ('answer_description', models.CharField(max_length=1000)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=1000)),
                ('points', models.IntegerField(default=0)),
                ('header_text', models.CharField(default='', max_length=1000)),
                ('footer_text', models.CharField(default='', max_length=1000)),
                ('success_msg', models.CharField(default='', max_length=1000)),
                ('fail_msg', models.CharField(default='', max_length=1000)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_text', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('score_question', models.IntegerField(default=0)),
                ('One_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='One_answer', to='exam.one_answer')),
                ('exam', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Exam', to='exam.Exam')),
                ('multi_choice_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi_choice_answer', to='exam.Multi_choice_answer')),
                ('userP', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentification.UserP')),
                ('userS', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentification.UserS')),
            ],
        ),
        migrations.AddField(
            model_name='one_answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Question'),
        ),
        migrations.AddField(
            model_name='multi_choice_answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Question'),
        ),
        migrations.AddField(
            model_name='free_text',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Question'),
        ),
    ]
