# Generated by Django 2.0.7 on 2018-08-17 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0003_auto_20180817_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserS', to='Authentification.UserP'),
        ),
    ]
