# Generated by Django 2.0.7 on 2018-08-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0005_auto_20180817_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='professor',
        ),
        migrations.AddField(
            model_name='userp',
            name='student',
            field=models.ManyToManyField(to='Authentification.UserS'),
        ),
    ]
