# Generated by Django 2.0.7 on 2018-08-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0001_initial'),
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yard',
            name='student',
            field=models.ManyToManyField(to='Authentification.UserS'),
        ),
    ]
